export const PLACEHOLDER_IMAGE = "/images/heromodel.png";

export const PRODUCTS = [
	{
		id: 1,
		name: "Signature Riot Fit",
		price: 49.99,
		originalPrice: 69.99,
		image: "/images/heromodel.png",
		category: "tees",
		badge: "Sale",
		badgePreset: "preset-filled-error-500",
		rating: 4.8,
		reviews: 124,
	},
	{
		id: 2,
		name: "Tactical Riot Vest",
		price: 89.99,
		originalPrice: null,
		image: "/images/vest2.png",
		category: "jackets",
		badge: "Best Seller",
		badgePreset: "preset-filled-primary-500",
		rating: 4.9,
		reviews: 231,
	},
	{
		id: 3,
		name: "Rebel Bomber Vest",
		price: 149.99,
		originalPrice: null,
		image: "/images/vest.png",
		category: "jackets",
		badge: "New",
		badgePreset: "preset-filled-tertiary-500",
		rating: 4.7,
		reviews: 56,
	},
	{
		id: 4,
		name: "Shredded Chain Jeans",
		price: 79.99,
		originalPrice: 99.99,
		image: "/images/pants.png",
		category: "bottoms",
		badge: "Sale",
		badgePreset: "preset-filled-error-500",
		rating: 4.5,
		reviews: 89,
	},
	{
		id: 5,
		name: "Havoc High Tops",
		price: 129.99,
		originalPrice: null,
		image: "/images/shoes.png",
		category: "footwear",
		badge: "New",
		badgePreset: "preset-filled-tertiary-500",
		rating: 4.6,
		reviews: 42,
	},
	{
		id: 6,
		name: "Anarchy Street Kicks",
		price: 74.99,
		originalPrice: null,
		image: "/images/shoes2.png",
		category: "footwear",
		badge: null,
		badgePreset: "",
		rating: 4.4,
		reviews: 78,
	},
];
